### ISSUE TITLE
Handling case sensitivity when serving the files

### ISSUE THREAD

**Issue by AidaNow** [ArnaudBuchholz/reserve#6]
When we are using REserve to serve files in Windows, due to case insensitive nature of Windows, REserve does not catch the case-sensitivity errors. However, if the same code is run on a Linux machine, then these errors are caught.

**Comment by ArnaudBuchholz** [comment]
Added the option `case-sensitive` on file handler (default is `false`). When set, it will verify that the path matches case sensitively the file system. Since it has a performance cost, it is not enabled by default.
